kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule init
  - git submodule update --recursive --remote

- name: build-test
  image: gradle:latest
  commands:
  - gradle assemble check --stacktrace

- name: upload
  image: plugins/s3
  when:
    branch:
    - master
    event:
    - push
  settings:
    bucket: drone
    access_key:
      from_secret: aws_access_key_id
    secret_key:
      from_secret: aws_secret_access_key
    source: launcher/build/distributions/launcher-*.tbz2
    target: /
    strip_prefix: launcher/build/distributions/
    path_style: true
    endpoint: https://minio.rwx.ovh