image: gradle:alpine

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: "clone"
  GIT_SUBMODULE_STRATEGY: "recursive"
  GIT_DEPTH: "3"

build:
  stage: build
  script:
    - gradle --build-cache assemble
    - tar xvf $CI_PROJECT_DIR/launcher/build/distributions/launcher-*.tbz2 -C $CI_PROJECT_DIR
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - $CI_PROJECT_DIR/build
      - $CI_PROJECT_DIR/.gradle
  artifacts:
    name: ${CI_PROJECT_NAME}-commit_${CI_COMMIT_SHA}
    paths:
      - $CI_PROJECT_DIR/lib
      - $CI_PROJECT_DIR/plugins
      - $CI_PROJECT_DIR/config.example.json
      - $CI_PROJECT_DIR/fastfood_localization.json
      - $CI_PROJECT_DIR/launcher-*.jar
